### ISSUE TITLE
Lapse ("for 90 consecutive calendar days")

### ISSUE THREAD

**Issue by anseljh** [licensezero/licensezero-noncommercial-public-license#1]
> ... The conditions of this
> paragraph are waived if licenses on other terms cease to be
> available via the following agent, or a successor named in a
> subsequent release, for 90 consecutive calendar days

For *which* 90 consecutive days? The most recent preceding 90 days, or *any* 90 days? 

**Scenario:** Larry Licensor goes on an extended offline vacation to Antarctica, and does not respond to licensing inquiries for 91 days. When Larry gets back, he picks up where he left off, and resumes his licensing business. Two years later, can a new licensee point to the 91-day lapse two years ago and say "I don't have to pay you"?

**Comment by kemitchell** [comment]
The intent was that any lapse of 90 days waives the condition.

The placeholder for a licensing _agent_ that follows the grace-period language addresses the (90-day?) vacation gotcha. licensezero.com or another agent stands ready to issue licenses on demand.

**Comment by kemitchell** [comment]
@anseljh, I've since dropped the automatic-waiver feature of the license, which is now based on the same "core" as L0-R.
